/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Color defaultcolor, clickedcolor, white, black;

    public Menu() {
        initComponents();
        defaultcolor = new Color(154, 217, 205);
        clickedcolor = new Color(51, 51, 51);
        white = new Color(255, 255, 255);
        black = new Color(0, 0, 0);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        URL url = this.getClass().getResource("/Images/caren.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LblNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblNivel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        P1 = new javax.swing.JPanel();
        LblPedido = new javax.swing.JLabel();
        P2 = new javax.swing.JPanel();
        LblCardapio = new javax.swing.JLabel();
        P3 = new javax.swing.JPanel();
        LblInsumo = new javax.swing.JLabel();
        P4 = new javax.swing.JPanel();
        LblDelivery = new javax.swing.JLabel();
        P5 = new javax.swing.JPanel();
        LblFornecedor = new javax.swing.JLabel();
        P6 = new javax.swing.JPanel();
        LblFuncionarios = new javax.swing.JLabel();
        LblLogout = new javax.swing.JLabel();
        TblMenu = new javax.swing.JTabbedPane();
        M1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        LblTotal2 = new javax.swing.JLabel();
        BtnFinalizar = new javax.swing.JButton();
        TxtNome = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TblPedido = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        TblCardapio = new javax.swing.JTable();
        SpnQuant = new javax.swing.JSpinner();
        BtnAdicionar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LblTotal = new javax.swing.JLabel();
        LblTotal1 = new javax.swing.JLabel();
        M2 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        TxtNomeComida = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtTipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtCusto = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtComposicao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnLimpar = new javax.swing.JButton();
        M3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        TxtNomeInsumo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtQuantidade = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TxtPreco = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtnLimparInsumo = new javax.swing.JButton();
        M4 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TxtTaxa = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        BtnLimparDelivery = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        TxtNomeDelivery = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        M5 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        BtnLimparFornecedor = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TxtNomeFornecedor = new javax.swing.JTextField();
        LblProduto = new javax.swing.JLabel();
        TxtProduto = new javax.swing.JTextField();
        TxtCNPJ = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        M6 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TblFuncionario = new javax.swing.JTable();
        BtnAlterar = new javax.swing.JButton();
        BtnExcluirFuncionario = new javax.swing.JButton();
        LblTotal3 = new javax.swing.JLabel();
        LblTotal4 = new javax.swing.JLabel();
        TxtValor = new javax.swing.JTextField();
        TxtCampo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblNome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LblNome.setForeground(new java.awt.Color(154, 217, 205));
        LblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblNome.setText("Usuário");
        jPanel2.add(LblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 15, 290, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(154, 217, 205));
        jLabel3.setText("Nível");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        LblNivel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LblNivel.setForeground(new java.awt.Color(154, 217, 205));
        LblNivel.setText("1");
        jPanel2.add(LblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(154, 217, 205));
        jLabel11.setText("C.A.R.E.N.");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 530, 70));

        jPanel3.setBackground(new java.awt.Color(154, 217, 205));
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        P1.setBackground(new java.awt.Color(154, 217, 205));
        P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1MouseClicked(evt);
            }
        });

        LblPedido.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        LblPedido.setForeground(new java.awt.Color(0, 0, 0));
        LblPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPedido.setText("Fazer Pedido");
        LblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblPedidoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LblPedidoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LblPedidoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LblPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(LblPedido)
                .addGap(14, 14, 14))
        );

        P2.setBackground(new java.awt.Color(154, 217, 205));

        LblCardapio.setFont(new java.awt.Font("Showcard Gothic", 0, 10)); // NOI18N
        LblCardapio.setForeground(new java.awt.Color(0, 0, 0));
        LblCardapio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCardapio.setText("Novo Item do Cardápio");
        LblCardapio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblCardapioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LblCardapioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LblCardapioMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout P2Layout = new javax.swing.GroupLayout(P2);
        P2.setLayout(P2Layout);
        P2Layout.setHorizontalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        P2Layout.setVerticalGroup(
            P2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(LblCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        P3.setBackground(new java.awt.Color(154, 217, 205));

        LblInsumo.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        LblInsumo.setForeground(new java.awt.Color(0, 0, 0));
        LblInsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblInsumo.setText("Novo Insumo");
        LblInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblInsumoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LblInsumoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LblInsumoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout P3Layout = new javax.swing.GroupLayout(P3);
        P3.setLayout(P3Layout);
        P3Layout.setHorizontalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LblInsumo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P3Layout.setVerticalGroup(
            P3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(LblInsumo)
                .addGap(14, 14, 14))
        );

        P4.setBackground(new java.awt.Color(154, 217, 205));

        LblDelivery.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        LblDelivery.setForeground(new java.awt.Color(0, 0, 0));
        LblDelivery.setText("Novo Delivery");
        LblDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblDeliveryMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LblDeliveryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LblDeliveryMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout P4Layout = new javax.swing.GroupLayout(P4);
        P4.setLayout(P4Layout);
        P4Layout.setHorizontalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LblDelivery)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P4Layout.setVerticalGroup(
            P4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(LblDelivery)
                .addGap(15, 15, 15))
        );

        P5.setBackground(new java.awt.Color(154, 217, 205));

        LblFornecedor.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        LblFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        LblFornecedor.setText("Novo Fornecedor");
        LblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblFornecedorMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LblFornecedorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LblFornecedorMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout P5Layout = new javax.swing.GroupLayout(P5);
        P5.setLayout(P5Layout);
        P5Layout.setHorizontalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LblFornecedor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P5Layout.setVerticalGroup(
            P5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LblFornecedor)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        P6.setBackground(new java.awt.Color(154, 217, 205));

        LblFuncionarios.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        LblFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        LblFuncionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblFuncionarios.setText("Funcionários");
        LblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblFuncionariosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LblFuncionariosMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LblFuncionariosMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout P6Layout = new javax.swing.GroupLayout(P6);
        P6.setLayout(P6Layout);
        P6Layout.setHorizontalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        P6Layout.setVerticalGroup(
            P6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(LblFuncionarios)
                .addGap(15, 15, 15))
        );

        LblLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leonardo\\Documents\\SiteRestaurante\\imagens\\logout.png")); // NOI18N
        LblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(P6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LblLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblLogout)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 470));

        TblMenu.setBackground(new java.awt.Color(255, 204, 0));
        TblMenu.setForeground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(172, 86, 6));
        jPanel16.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel16ComponentShown(evt);
            }
        });

        LblTotal2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LblTotal2.setForeground(new java.awt.Color(242, 231, 75));
        LblTotal2.setText("Nome:");

        BtnFinalizar.setBackground(new java.awt.Color(242, 231, 75));
        BtnFinalizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
        BtnFinalizar.setText("Fazer Pedido");
        BtnFinalizar.setToolTipText("");
        BtnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalizarActionPerformed(evt);
            }
        });

        TxtNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeActionPerformed(evt);
            }
        });

        TblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Quantidade", "Valor (R$)"
            }
        ));
        jScrollPane3.setViewportView(TblPedido);

        TblCardapio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "ID", "Valor (R$)"
            }
        ));
        TblCardapio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TblCardapioFocusGained(evt);
            }
        });
        jScrollPane4.setViewportView(TblCardapio);

        BtnAdicionar.setBackground(new java.awt.Color(242, 231, 75));
        BtnAdicionar.setForeground(new java.awt.Color(0, 0, 0));
        BtnAdicionar.setText("Adicionar");
        BtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdicionarActionPerformed(evt);
            }
        });

        BtnExcluir.setBackground(new java.awt.Color(242, 231, 75));
        BtnExcluir.setForeground(new java.awt.Color(0, 0, 0));
        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 231, 75));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Novo Pedido");

        LblTotal.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LblTotal.setForeground(new java.awt.Color(242, 231, 75));
        LblTotal.setText("0");

        LblTotal1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        LblTotal1.setForeground(new java.awt.Color(242, 231, 75));
        LblTotal1.setText("Total: R$");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(SpnQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)
                                        .addComponent(BtnAdicionar)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(LblTotal2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(57, 57, 57)
                                .addComponent(LblTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(BtnExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SpnQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAdicionar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblTotal1)
                            .addComponent(LblTotal)
                            .addComponent(BtnExcluir))))
                .addGap(22, 22, 22)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTotal2)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(BtnFinalizar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout M1Layout = new javax.swing.GroupLayout(M1);
        M1.setLayout(M1Layout);
        M1Layout.setHorizontalGroup(
            M1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        M1Layout.setVerticalGroup(
            M1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TblMenu.addTab("tab1", M1);

        jPanel17.setBackground(new java.awt.Color(172, 86, 6));

        TxtNomeComida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(242, 231, 75));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cadastrar");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 231, 75));
        jLabel4.setText("Composição");

        TxtTipo.setBackground(new java.awt.Color(242, 231, 75));
        TxtTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtTipo.setForeground(new java.awt.Color(0, 0, 0));
        TxtTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Hamburguer", "Sobremesa", "Porção", "Bebida", "Combo" }));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 231, 75));
        jLabel8.setText("Tipo de Comida");

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 231, 75));
        jLabel5.setText("R$");

        TxtCusto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCusto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TxtComposicao.setColumns(20);
        TxtComposicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtComposicao.setRows(5);
        jScrollPane1.setViewportView(TxtComposicao);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 231, 75));
        jLabel2.setText("Valor da Comida");

        jLabel13.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 231, 75));
        jLabel13.setText("Nome da Comida");

        BtnLimpar.setBackground(new java.awt.Color(242, 231, 75));
        BtnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnLimpar.setForeground(new java.awt.Color(0, 0, 0));
        BtnLimpar.setText("Limpar");
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(TxtNomeComida, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel17Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNomeComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout M2Layout = new javax.swing.GroupLayout(M2);
        M2.setLayout(M2Layout);
        M2Layout.setHorizontalGroup(
            M2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        M2Layout.setVerticalGroup(
            M2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, M2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TblMenu.addTab("tab2", M2);

        jPanel18.setBackground(new java.awt.Color(172, 86, 6));

        TxtNomeInsumo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 231, 75));
        jLabel6.setText("Quantidade de Insumo");

        TxtQuantidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtQuantidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 231, 75));
        jLabel7.setText("Valor de Insumo (u)");

        jButton3.setBackground(new java.awt.Color(242, 231, 75));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cadastrar");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(242, 231, 75));
        jLabel14.setText("R$");

        TxtPreco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtPreco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 231, 75));
        jLabel9.setText("Nome do Insumo");

        jLabel15.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(242, 231, 75));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cadastro de Insumo");

        BtnLimparInsumo.setBackground(new java.awt.Color(242, 231, 75));
        BtnLimparInsumo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnLimparInsumo.setForeground(new java.awt.Color(0, 0, 0));
        BtnLimparInsumo.setText("Limpar");
        BtnLimparInsumo.setToolTipText("");
        BtnLimparInsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparInsumoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLimparInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNomeInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNomeInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(TxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(BtnLimparInsumo))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout M3Layout = new javax.swing.GroupLayout(M3);
        M3.setLayout(M3Layout);
        M3Layout.setHorizontalGroup(
            M3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        M3Layout.setVerticalGroup(
            M3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TblMenu.addTab("tab3", M3);

        jPanel19.setBackground(new java.awt.Color(172, 86, 6));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Taxa de Entrega");

        TxtTaxa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtTaxa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("R$");

        jButton4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton4.setText("Cadastrar");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnLimparDelivery.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnLimparDelivery.setText("Limpar");
        BtnLimparDelivery.setToolTipText("");
        BtnLimparDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparDeliveryActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nome da Empresa");

        TxtNomeDelivery.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtNomeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeDeliveryActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cadastro de Delivery");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(BtnLimparDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtNomeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(TxtNomeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTaxa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(42, 42, 42)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(BtnLimparDelivery))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout M4Layout = new javax.swing.GroupLayout(M4);
        M4.setLayout(M4Layout);
        M4Layout.setHorizontalGroup(
            M4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        M4Layout.setVerticalGroup(
            M4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TblMenu.addTab("tab4", M4);

        jPanel20.setBackground(new java.awt.Color(172, 86, 6));

        BtnLimparFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BtnLimparFornecedor.setText("Limpar");
        BtnLimparFornecedor.setToolTipText("");
        BtnLimparFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparFornecedorActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setText("Cadastrar");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nome");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CNPJ");

        TxtNomeFornecedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        LblProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblProduto.setForeground(new java.awt.Color(255, 255, 255));
        LblProduto.setText("Produto");

        TxtProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        TxtCNPJ.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cadastro de Fornecedor");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblProduto)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TxtCNPJ, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel20Layout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(390, 390, 390))
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TxtNomeFornecedor, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel20Layout.createSequentialGroup()
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnLimparFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TxtProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(12, 12, 12)
                .addComponent(TxtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(8, 8, 8)
                .addComponent(TxtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(BtnLimparFornecedor))
                .addGap(149, 149, 149))
        );

        javax.swing.GroupLayout M5Layout = new javax.swing.GroupLayout(M5);
        M5.setLayout(M5Layout);
        M5Layout.setHorizontalGroup(
            M5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        M5Layout.setVerticalGroup(
            M5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TblMenu.addTab("tab6", M5);

        jPanel21.setBackground(new java.awt.Color(172, 86, 6));

        TblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "RG", "Salário (R$)", "CEP", "Senha", "Nível de Acesso"
            }
        ));
        jScrollPane5.setViewportView(TblFuncionario);

        BtnAlterar.setText("Alterar");
        BtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarActionPerformed(evt);
            }
        });

        BtnExcluirFuncionario.setText("Excluir");
        BtnExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirFuncionarioActionPerformed(evt);
            }
        });

        LblTotal3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblTotal3.setForeground(new java.awt.Color(255, 255, 255));
        LblTotal3.setText("Campo:");

        LblTotal4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LblTotal4.setForeground(new java.awt.Color(255, 255, 255));
        LblTotal4.setText("Novo valor:");

        TxtValor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtValorActionPerformed(evt);
            }
        });

        TxtCampo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TxtCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "CPF", "Nome", "RG", "Salário", "CEP", "Senha", "Nível de acesso" }));
        TxtCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCampoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(BtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnExcluirFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTotal4)
                            .addComponent(LblTotal3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCampo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TxtValor, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAlterar)
                    .addComponent(BtnExcluirFuncionario))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTotal3)
                    .addComponent(TxtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTotal4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout M6Layout = new javax.swing.GroupLayout(M6);
        M6.setLayout(M6Layout);
        M6Layout.setHorizontalGroup(
            M6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        M6Layout.setVerticalGroup(
            M6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TblMenu.addTab("tab5", M6);

        jPanel1.add(TblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 530, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void redimensionarColuna() {

        TblCardapio.getColumnModel().getColumn(0)
                .setPreferredWidth(150);
        TblCardapio.getColumnModel().getColumn(1)
                .setPreferredWidth(20);

        TblPedido.getColumnModel().getColumn(0)
                .setPreferredWidth(150);
        TblPedido.getColumnModel().getColumn(1)
                .setPreferredWidth(20);

    }

    private void carregarCardapio() {
        DefaultTableModel tblCardapio = (DefaultTableModel) TblCardapio.getModel();
        tblCardapio.setRowCount(0);

        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        try {

            PreparedStatement stml = conexao.prepareStatement("select * from Cardapio");
            ResultSet rs = stml.executeQuery();

            while (rs.next()) {

                String coluna0 = rs.getString(2);
                String coluna1 = Integer.toString(rs.getInt(1));

                //Formatar o valor para duas casas decimais e com a unidade R$
                //DecimalFormat db = new DecimalFormat(".00");
                String coluna2 = rs.getFloat(4) + "0";

                //Inserir os valores na JTable
                tblCardapio.addRow(new String[]{coluna0, coluna1, coluna2});

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void LblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPedidoMouseClicked
        // TODO add your handling code here:
        TblMenu.setSelectedIndex(0);

        DefaultTableModel tblPedido = (DefaultTableModel) TblPedido.getModel();
        carregarCardapio();
    }//GEN-LAST:event_LblPedidoMouseClicked

    private void LblCardapioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCardapioMouseClicked
        // TODO add your handling code here:
        TblMenu.setSelectedIndex(1);
    }//GEN-LAST:event_LblCardapioMouseClicked

    private void LblInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInsumoMouseClicked
        // TODO add your handling code here:
        TblMenu.setSelectedIndex(2);
    }//GEN-LAST:event_LblInsumoMouseClicked

    private void LblDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDeliveryMouseClicked
        // TODO add your handling code here:
        TblMenu.setSelectedIndex(3);
    }//GEN-LAST:event_LblDeliveryMouseClicked

    private void LblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFornecedorMouseClicked
        // TODO add your handling code here:
        TblMenu.setSelectedIndex(4);
    }//GEN-LAST:event_LblFornecedorMouseClicked

    private void LblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFuncionariosMouseClicked
        // TODO add your handling code here:
        TblMenu.setSelectedIndex(5);
        carregarFuncionarios();
    }//GEN-LAST:event_LblFuncionariosMouseClicked

    private void LblPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPedidoMousePressed
        // TODO add your handling code here:
        P1.setBackground(clickedcolor);
        P2.setBackground(defaultcolor);
        P3.setBackground(defaultcolor);
        P4.setBackground(defaultcolor);
        P5.setBackground(defaultcolor);
        P6.setBackground(defaultcolor);

        LblPedido.setForeground(white);
    }//GEN-LAST:event_LblPedidoMousePressed

    private void LblPedidoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPedidoMouseReleased
        // TODO add your handling code here:
        P1.setBackground(defaultcolor);
        LblPedido.setForeground(black);
    }//GEN-LAST:event_LblPedidoMouseReleased

    private void LblCardapioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCardapioMousePressed
        // TODO add your handling code here:
        P1.setBackground(defaultcolor);
        P2.setBackground(clickedcolor);
        P3.setBackground(defaultcolor);
        P4.setBackground(defaultcolor);
        P5.setBackground(defaultcolor);
        P6.setBackground(defaultcolor);

        LblCardapio.setForeground(white);
    }//GEN-LAST:event_LblCardapioMousePressed

    private void LblCardapioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblCardapioMouseReleased
        // TODO add your handling code here:
        P2.setBackground(defaultcolor);
        LblCardapio.setForeground(black);
    }//GEN-LAST:event_LblCardapioMouseReleased

    private void LblInsumoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInsumoMousePressed
        // TODO add your handling code here:
        P1.setBackground(defaultcolor);
        P2.setBackground(defaultcolor);
        P3.setBackground(clickedcolor);
        P4.setBackground(defaultcolor);
        P5.setBackground(defaultcolor);
        P6.setBackground(defaultcolor);

        LblInsumo.setForeground(white);
    }//GEN-LAST:event_LblInsumoMousePressed

    private void LblInsumoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInsumoMouseReleased
        // TODO add your handling code here:
        P3.setBackground(defaultcolor);
        LblInsumo.setForeground(black);
    }//GEN-LAST:event_LblInsumoMouseReleased

    private void LblDeliveryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDeliveryMousePressed
        // TODO add your handling code here:
        P1.setBackground(defaultcolor);
        P2.setBackground(defaultcolor);
        P3.setBackground(defaultcolor);
        P4.setBackground(clickedcolor);
        P5.setBackground(defaultcolor);
        P6.setBackground(defaultcolor);

        LblDelivery.setForeground(white);
    }//GEN-LAST:event_LblDeliveryMousePressed

    private void LblDeliveryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDeliveryMouseReleased
        // TODO add your handling code here:
        P4.setBackground(defaultcolor);
        LblDelivery.setForeground(black);
    }//GEN-LAST:event_LblDeliveryMouseReleased

    private void LblFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFornecedorMousePressed
        // TODO add your handling code here:
        P1.setBackground(defaultcolor);
        P2.setBackground(defaultcolor);
        P3.setBackground(defaultcolor);
        P4.setBackground(defaultcolor);
        P5.setBackground(clickedcolor);
        P6.setBackground(defaultcolor);

        LblFornecedor.setForeground(white);
    }//GEN-LAST:event_LblFornecedorMousePressed

    private void LblFornecedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFornecedorMouseReleased
        // TODO add your handling code here:
        P5.setBackground(defaultcolor);
        LblFornecedor.setForeground(black);
    }//GEN-LAST:event_LblFornecedorMouseReleased

    private void LblFuncionariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFuncionariosMousePressed
        // TODO add your handling code here:
        P1.setBackground(defaultcolor);
        P2.setBackground(defaultcolor);
        P3.setBackground(defaultcolor);
        P4.setBackground(defaultcolor);
        P5.setBackground(defaultcolor);
        P6.setBackground(clickedcolor);

        LblFuncionarios.setForeground(white);
    }//GEN-LAST:event_LblFuncionariosMousePressed

    private void LblFuncionariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblFuncionariosMouseReleased
        // TODO add your handling code here:
        P6.setBackground(defaultcolor);
        LblFuncionarios.setForeground(black);
    }//GEN-LAST:event_LblFuncionariosMouseReleased

    private void BtnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalizarActionPerformed

        //Adicionando os itens ao campo de Itens
        int linhasPedido = TblPedido.getRowCount();

        DefaultTableModel tblPedido = (DefaultTableModel) TblPedido.getModel();

        String itens = Integer.toString((Integer) tblPedido.getValueAt(0, 1)) + "x " + (String) tblPedido.getValueAt(0, 0);

        for (int i = 1; i < linhasPedido; i++) {
            itens += ", " + Integer.toString((Integer) tblPedido.getValueAt(i, 1)) + "x " + (String) tblPedido.getValueAt(i, 0);
        }
        //System.out.println(itens);

        //Obtendo o valor total
        double total = Double.parseDouble(LblTotal.getText());

        //Inserir no banco de dados o novo pedido
        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        obj.novoPedido(conexao, itens, total);

        obj.consultaPedidos(conexao);

        String nome = TxtNome.getText();

        PedidoSendoFeito criar = new PedidoSendoFeito();

        criar.LblNome.setText(nome);

        //dispose();
        criar.setVisible(true);

        TxtNome.setText("");
        tblPedido.setRowCount(0);
        LblTotal.setText("0");


    }//GEN-LAST:event_BtnFinalizarActionPerformed

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void BtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdicionarActionPerformed
        // TODO add your handling code here:

        try {

            double total = Double.parseDouble(LblTotal.getText());

            int quantidade = (int) SpnQuant.getValue();
            //System.out.println(quantidade);

            int index = TblCardapio.getSelectedRow();
            Object[] row = new Object[3];

            DefaultTableModel tblCardapio = (DefaultTableModel) TblCardapio.getModel();
            DefaultTableModel tblPedido = (DefaultTableModel) TblPedido.getModel();

            row[0] = tblCardapio.getValueAt(index, 0);
            row[1] = quantidade;
            row[2] = tblCardapio.getValueAt(index, 2);

            double v1 = Double.valueOf((String) tblCardapio.getValueAt(index, 2));

            total += v1 * quantidade;

            LblTotal.setText(String.valueOf(total) + "0");

            tblPedido.addRow(row);

            SpnQuant.setValue(0);

        } catch (Exception e) {
            System.out.println("Erro!\nO erro em questão se trata de: " + e);
        }

    }//GEN-LAST:event_BtnAdicionarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblPedido = (DefaultTableModel) TblPedido.getModel();

        if (TblPedido.getSelectedRowCount() == 1) {
            int index = TblPedido.getSelectedRow();
            int index2 = TblPedido.getSelectedColumn();

            //Remover o valor do total
            double total = Double.parseDouble(LblTotal.getText());

            int quantidade = (Integer) tblPedido.getValueAt(index, 1);
            double valor = Double.valueOf((String) tblPedido.getValueAt(index, 2));

            tblPedido.removeRow(TblPedido.getSelectedRow());
            total -= quantidade * valor;

            LblTotal.setText(String.valueOf(total) + "0");
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void jPanel16ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel16ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel16ComponentShown

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3ComponentShown

    private void TblCardapioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TblCardapioFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_TblCardapioFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        redimensionarColuna();
        carregarCardapio();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        String nome = TxtNomeComida.getText();
        String tipo = (String) TxtTipo.getSelectedItem();
        int custo = (int) TxtCusto.getValue();
        String composicao = TxtComposicao.getText();

        obj.novoItemCardapio(conexao, nome, tipo, custo, composicao);

        //obj.consultaCardapio(conexao);
        TxtNomeComida.setText("");
        TxtTipo.setSelectedIndex(0);
        TxtCusto.setValue(0);
        TxtComposicao.setText("");
        JOptionPane.showMessageDialog(null, "Item adicionado ao cardápio.");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        // TODO add your handling code here:
        TxtNomeComida.setText("");
        TxtTipo.setSelectedIndex(0);
        TxtCusto.setValue(0);
        TxtComposicao.setText("");
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        String nome = TxtNomeInsumo.getText();
        int custo = (int) TxtPreco.getValue();
        int quantidade = (int) TxtQuantidade.getValue();

        obj.novoInsumo(conexao, nome, custo, quantidade);

        obj.consultaInsumo(conexao);

        TxtNomeInsumo.setText("");
        TxtPreco.setValue(0);
        TxtQuantidade.setValue(0);

        JOptionPane.showMessageDialog(null, "Insumo cadastrado.");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnLimparInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparInsumoActionPerformed
        // TODO add your handling code here:
        TxtNomeInsumo.setText("");
        TxtPreco.setValue(0);
        TxtQuantidade.setValue(0);
    }//GEN-LAST:event_BtnLimparInsumoActionPerformed

    private void BtnLimparDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparDeliveryActionPerformed

        TxtNomeDelivery.setText("");
        TxtTaxa.setValue(0);

    }//GEN-LAST:event_BtnLimparDeliveryActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        String nome = TxtNomeDelivery.getText();
        int taxa = (int) TxtTaxa.getValue();

        obj.novoServicoDelivery(conexao, nome, taxa);

        //obj.consultaDelivery(conexao);
        JOptionPane.showMessageDialog(null, "Delivery cadastrado.");

        TxtNomeDelivery.setText("");
        TxtTaxa.setValue(0);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void TxtNomeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeDeliveryActionPerformed

    private void BtnLimparFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparFornecedorActionPerformed

        TxtNomeFornecedor.setText("");
        TxtCNPJ.setText("");
        TxtProduto.setText("");

    }//GEN-LAST:event_BtnLimparFornecedorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        String nome = TxtNomeFornecedor.getText();
        long cnpj = Long.parseLong(TxtCNPJ.getText());
        String produto = TxtProduto.getText();

        obj.novoFornecedor(conexao, cnpj, nome, produto);

        obj.consultaFornecedor(conexao);

        TxtNomeFornecedor.setText("");
        TxtCNPJ.setText("");
        TxtProduto.setText("");


    }//GEN-LAST:event_jButton5ActionPerformed

    private void carregarFuncionarios() {
        DefaultTableModel tblFuncionario = (DefaultTableModel) TblFuncionario.getModel();

        tblFuncionario.setRowCount(0);

        Conectar obj = new Conectar();

        Connection conexao = obj.connectionMySql();

        try {

            PreparedStatement stml = conexao.prepareStatement("select * from Funcionarios");
            ResultSet rs = stml.executeQuery();

            while (rs.next()) {

                String coluna0 = Long.toString(rs.getLong(1));       //CPF
                String coluna1 = rs.getString(2);                    //Nome
                String coluna2 = rs.getString(3);                    //RG
                String coluna3 = Float.toString(rs.getFloat(4));     //Salário
                String coluna4 = Long.toString(rs.getLong(5));       //CEP
                String coluna5 = rs.getString(6);                    //Senha
                String coluna6 = Integer.toString(rs.getInt(7));     //Nível de acesso

                System.out.println(
                        "\n   CPF:" + rs.getLong(1)
                        + "\n   Nome:" + rs.getString(2)
                        + "\n   RG:" + rs.getString(3)
                        + "\n   Salário:" + rs.getFloat(4)
                        + "\n   CEP: " + rs.getInt(5)
                );

                //Formatar o valor para duas casas decimais e com a unidade R$
                //DecimalFormat db = new DecimalFormat(".00");
                //Inserir os valores na JTable
                tblFuncionario.addRow(new String[]{coluna0, coluna1, coluna2, coluna3, coluna4, coluna5, coluna6});

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void alterarCampo(String Campo, String novoValor) throws SQLException {

        try {

            System.out.println("\n\nFUNÇÃO\nCampo: " + Campo + "\nValor: " + novoValor);

            //Obter a chave primária do registro a ser alterado
            int index = TblFuncionario.getSelectedRow();
            DefaultTableModel tblFuncionario = (DefaultTableModel) TblFuncionario.getModel();
            String CPF = (String) tblFuncionario.getValueAt(index, 0);
            long cpf = Long.parseLong(CPF);
            System.out.println("CPF selecionado: " + cpf);
            //Preparar a conexão com o MySQL
            Conectar obj = new Conectar();
            Connection conexao = obj.connectionMySql();

            PreparedStatement pstm;

            //Executar a query de atualizar o devido registro
            switch (Campo) {

                case "Nome":
                    System.out.println("Executando case para Nome");
                    pstm = conexao.prepareStatement("UPDATE Funcionarios SET Nome_fun= ? WHERE CPF= ?;");
                    pstm.setString(1, novoValor);
                    pstm.setLong(2, cpf);
                    pstm.execute();

                    break;

                case "RG":
                    pstm = conexao.prepareStatement("UPDATE Funcionarios SET RG= ? WHERE CPF= ?;");
                    pstm.setString(1, novoValor);
                    pstm.setLong(2, cpf);
                    pstm.execute();

                    break;

                case "Salário":

                    float salario = Float.parseFloat(novoValor);
                    pstm = conexao.prepareStatement("UPDATE Funcionarios SET Salario= ? WHERE CPF= ?;");
                    pstm.setFloat(1, salario);
                    pstm.setLong(2, cpf);
                    pstm.execute();
                    break;

                case "CEP":

                    long cep = Long.parseLong(novoValor);
                    pstm = conexao.prepareStatement("UPDATE Funcionarios SET CEP= ? WHERE CPF= ?;");
                    pstm.setLong(1, cep);
                    pstm.setLong(2, cpf);
                    pstm.execute();
                    break;

                case "Senha":
                    pstm = conexao.prepareStatement("UPDATE Funcionarios SET Senha= ? WHERE CPF= ?;");
                    pstm.setString(1, novoValor);
                    pstm.setLong(2, cpf);
                    pstm.execute();
                    break;

                case "Nível de acesso":
                    int nivel = Integer.parseInt(novoValor);
                    pstm = conexao.prepareStatement("UPDATE Funcionarios SET Nivel= ? WHERE CPF= ?;");
                    pstm.setInt(1, nivel);
                    pstm.setLong(2, cpf);
                    pstm.execute();
                    break;
            }
        } catch (Exception e) {
            System.out.println("Erro!\nO erro em questão se trata de: " + e);
        }

    }
    private void BtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarActionPerformed
        // TODO add your handling code here:

        try {

            String campo = (String) TxtCampo.getSelectedItem();
            String novoValor = TxtValor.getText();

            alterarCampo(campo, novoValor);
            carregarFuncionarios();

        } catch (Exception e) {
            System.out.println("Erro!\nO erro em questão se trata de: " + e);
        }
        TxtValor.setText("");
        TxtCampo.setSelectedIndex(0);

    }//GEN-LAST:event_BtnAlterarActionPerformed

    public void excluirRegistro() {
        try {

            //Obter a chave primária do registro a ser alterado
            int index = TblFuncionario.getSelectedRow();
            DefaultTableModel tblFuncionario = (DefaultTableModel) TblFuncionario.getModel();
            String CPF = (String) tblFuncionario.getValueAt(index, 0);
            long cpf = Long.parseLong(CPF);
            System.out.println("CPF selecionado: " + cpf);

            //Preparar a conexão com o MySQL
            Conectar obj = new Conectar();
            Connection conexao = obj.connectionMySql();

            //Executar a query de atualizar o devido registro
            PreparedStatement pstm = conexao.prepareStatement("DELETE FROM Funcionarios WHERE CPF= ?;");
            pstm.setLong(1, cpf);
            pstm.execute();

        } catch (Exception e) {
            System.out.println("Erro!\nO erro em questão se trata de: " + e);
        }
    }

    private void BtnExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirFuncionarioActionPerformed
        // TODO add your handling code here

        excluirRegistro();
        carregarFuncionarios();
    }//GEN-LAST:event_BtnExcluirFuncionarioActionPerformed

    private void TxtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorActionPerformed

    private void TxtCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCampoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formWindowActivated

    private void P1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_P1MouseClicked

    private void LblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblLogoutMouseClicked
        // TODO add your handling code here:
        Login JanLogin = new Login();
        
        dispose();
        
        JanLogin.setVisible(true);
    }//GEN-LAST:event_LblLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionar;
    private javax.swing.JButton BtnAlterar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnExcluirFuncionario;
    private javax.swing.JButton BtnFinalizar;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnLimparDelivery;
    private javax.swing.JButton BtnLimparFornecedor;
    private javax.swing.JButton BtnLimparInsumo;
    private javax.swing.JLabel LblCardapio;
    public javax.swing.JLabel LblDelivery;
    public javax.swing.JLabel LblFornecedor;
    public javax.swing.JLabel LblFuncionarios;
    private javax.swing.JLabel LblInsumo;
    private javax.swing.JLabel LblLogout;
    public javax.swing.JLabel LblNivel;
    public javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblPedido;
    private javax.swing.JLabel LblProduto;
    private javax.swing.JLabel LblTotal;
    private javax.swing.JLabel LblTotal1;
    private javax.swing.JLabel LblTotal2;
    private javax.swing.JLabel LblTotal3;
    private javax.swing.JLabel LblTotal4;
    private javax.swing.JPanel M1;
    private javax.swing.JPanel M2;
    private javax.swing.JPanel M3;
    private javax.swing.JPanel M4;
    private javax.swing.JPanel M5;
    private javax.swing.JPanel M6;
    private javax.swing.JPanel P1;
    private javax.swing.JPanel P2;
    private javax.swing.JPanel P3;
    public javax.swing.JPanel P4;
    public javax.swing.JPanel P5;
    public javax.swing.JPanel P6;
    private javax.swing.JSpinner SpnQuant;
    public javax.swing.JTable TblCardapio;
    public javax.swing.JTable TblFuncionario;
    private javax.swing.JTabbedPane TblMenu;
    public javax.swing.JTable TblPedido;
    private javax.swing.JTextField TxtCNPJ;
    private javax.swing.JComboBox<String> TxtCampo;
    private javax.swing.JTextArea TxtComposicao;
    private javax.swing.JSpinner TxtCusto;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNomeComida;
    private javax.swing.JTextField TxtNomeDelivery;
    private javax.swing.JTextField TxtNomeFornecedor;
    private javax.swing.JTextField TxtNomeInsumo;
    private javax.swing.JSpinner TxtPreco;
    private javax.swing.JTextField TxtProduto;
    private javax.swing.JSpinner TxtQuantidade;
    private javax.swing.JSpinner TxtTaxa;
    private javax.swing.JComboBox<String> TxtTipo;
    private javax.swing.JTextField TxtValor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
